### ISSUE TITLE
Delete Singularity repo?

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/charliecloud#26]
If there are no objections, I'd like to delete the JCSDA/singularity repository.

The public singularity and charliecloud containers are now generated together, in one action, using this build script in the charliecloud repository:
https://github.com/JCSDA/charliecloud/blob/develop/build_public_container.sh

The webhook that triggers an automated build from the Singularity repo to Singularity Hub is no longer necessary.  Now the public containers are stored on Sylabs cloud instead of Singularity Hub and can be accessed through push and pull operations initiated by the build scripts.

We have not yet generated private (intel) singularity containers yet but I plan to do so.  The procedure I intend to follow is to start from the hcp-container-maker python scripts in the charliecloud repository and create a Singularity recipe file from them.   

So, there is no longer any need for the Singularity repository.  Give a thumbs up if you agree and then I'll delete it.

**Comment by xinzhang8noaa** [comment]
No  problem !

**Comment by srherbener** [comment]
I'm good with deleting the singularity repo. Thanks
