### ISSUE TITLE
Install xarrray in clang contianer 

### ISSUE THREAD

**Issue by mer-a-o** [JCSDA/charliecloud#31]

**Comment by mmiesch** [comment]
Why the clang container in particular?  Should we just add it to the general list of python packages in jedi-stack?

**Comment by mer-a-o** [comment]
I was about to add other containers too. I am debugging CodeBuild errors in https://github.com/JCSDA/ioda-converters/pull/265 and adding requirements for each container one-by-one.

**Comment by mmiesch** [comment]
I just added it to [jedi-stack](https://github.com/JCSDA/jedi-stack/blob/72699f2065a27e5468ceeffb0d05bd495b0c7e62/buildscripts/libs/build_pyjedi.sh#L26).  This should take care of it for all containers.   It will take effect later this week as part of our mini-merge sprint with eckit.
