### ISSUE TITLE
Rebuild containers for jedi release

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA/charliecloud#39]
New packages have been added to the stack, and package versions have been bumped for the jedi release. Once JCSDA/jedi-stack#152, JCSDA/jedi-stack#146, JCSDA/jedi-stack#143, JCSDA/jedi-stack#141, et al. are resolved, the containers should be rebuilt.

**Comment by mmiesch** [comment]
Yep - this is planned: https://github.com/JCSDA/containers/issues/39 Maybe this is a duplicate issue?

**Comment by rhoneyager** [comment]
I somehow missed #38. Huh. 

Could we do a rebuild before the release to add the new libraries for the CI testing?

**Comment by wsmigaj** [comment]
> Could we do a rebuild before the release to add the new libraries for the CI testing?

That would be really handy for the CI testing of PRs related to `Parameters`.
