### ISSUE TITLE
New development containers

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/charliecloud#40]
To add to the new containers

- lcov 1.15
- json schema validator
- gsl_lite
- pybind11
- make stack size unlimited

**Comment by mmiesch** [comment]
@mer-a-o @wsmigaj - I'd like to consolidate all the changes needed to the development containers here in one place so when I rebuild them I don't forget anything.   Am I missing anything?

**Comment by mer-a-o** [comment]
@rhoneyager, you mentioned another package that will be needed soon. I don't remember its name.

**Comment by mmiesch** [comment]
> @rhoneyager, you mentioned another package that will be needed soon. I don't remember its name.

Ah yes - it is gsl-lite?  Should we add that to the containers?

**Comment by wsmigaj** [comment]
@mmiesch All the things I requested are already on your list. Thanks for checking with me!

**Comment by rhoneyager** [comment]
@mmiesch Yes. See jedi-stack issue re: version.

**Comment by danholdaway** [comment]
@mmiesch can you add fms please?

**Comment by mmiesch** [comment]
Done - thanks @danholdaway - I'll "assign" other core team members to this issue as well to see if anyone else has requests to add anything

**Comment by srherbener** [comment]
@mmiesch, thanks for this update.

When you say the containers will be updated, does this also include the module configurations on the HPC systems?

I just want to know for planning purposes with the ioda-engines repo (which uses gsl-lite) for the release.

Thanks!

**Comment by mmiesch** [comment]
@srherbener - this is separate from the hpc modules, though related.  When I re-build the containers, I will use the develop branch of jedi-stack so it will automatically get all the updated versions for hdf5, netcdf, ecbuild, eckit, etc.  This question really addresses new things that the containers do not have now but should have.

I believe most, if not all of the HPC modules now have gsl-lite.  If anyone notices one that does not then let me know - it's easy to add.

**Comment by srherbener** [comment]
@mmiesch thanks for the explanation. I think the list looks good (nothing to add).
