### ISSUE TITLE
New devel containers

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/charliecloud#50]
Build new gnu and clang development containers with these new features:

- [x] ubuntu 20.04 OS
- [x] bufrlib replaced with bufr
- [x] add clang-tidy

Problems solved: CI is failing in some places because of the deprecated bufrlib ([example](https://github.com/JCSDA-internal/ioda-converters/pull/388))

Note that the intel devel containers are already being rebuilt, as already covered in a [separate issue](https://github.com/JCSDA-internal/containers/issues/49)

**Comment by mmiesch** [comment]
I'm trying to build new containers with bufrlib replaced by bufr but now I'm getting this.  @aerorahul @srherbener - any ideas?  I could have sworn I tried this before in the containers and it worked - the only difference now being I'm using ubuntu 20.04 but I don't know why that would make a difference:

```bash
#10 80.03 Cloning into 'NCEPLIBS-bufr'...
#10 80.05 Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
#10 81.28 + [[ F =~ [yYtT] ]]
#10 81.28 + [[ -d NCEPLIBS-bufr ]]
#10 81.28 + cd NCEPLIBS-bufr
#10 81.28 + git fetch
#10 81.52 + git checkout --detach bufr_v11.4.0.jcsda1
#10 81.52 fatal: git checkout: --detach does not take a path argument 'bufr_v11.4.0.jcsda1'
#10 81.52 BUILD FAIL!  Lib: bufr-jcsda-internal Error:128
```

**Comment by mmiesch** [comment]
Looks like the tag is wrong.  It should be this @aerorahul @srherbener do you agree?

```
git checkout --detach 11.4.0.jcsda1
```

**Comment by aerorahul** [comment]
Is that a valid tag `bufr_v11.4.0.jcsda1`?
I think you want  `11.4.0.jcsda1`

**Comment by srherbener** [comment]
I agree. Clone from jcsda-internal/NCEPLIBS-bufr and use the tag 11.4.0.jcsda1.

**Comment by mmiesch** [comment]
Ok - looks to be working now.   I have a bugfix branch in jedi-stack.

While I'm at it, should I delete the bufrlib build script, modulefile, etc?

**Comment by srherbener** [comment]
@cmgas is running into this issue too, what is the bugfix branch in jedi-stack so she can try it out.

**Comment by mmiesch** [comment]
> @cmgas is running into this issue too, what is the bugfix branch in jedi-stack so she can try it out.

It's called `bugfix/update-udunits` because the udunits build is also failing. 

I have a meeting now but after the meeting I'll do a PR in jedi-stack.   @srherbener @aerorahul - should I delete all the old bufrlib stuff in favor of bufr?

Also - I think this bugfix branch also addresses email comments by @rickgrubin

**Comment by aerorahul** [comment]
@mmiesch Deleting `bufrlib` stuff is fine with me.

**Comment by srherbener** [comment]
I vote to delete the old bufrlib stuff in favor of bufr. All of the converter code builds with bufr and passes tests.

**Comment by rickgrubin** [comment]
> > @cmgas is running into this issue too, what is the bugfix branch in jedi-stack so she can try it out.
> 
> It's called `bugfix/update-udunits` because the udunits build is also failing.
> 
> I have a meeting now but after the meeting I'll do a PR in jedi-stack. @srherbener @aerorahul - should I delete all the old bufrlib stuff in favor of bufr?
> 
> Also - I think this bugfix branch also addresses email comments by @rickgrubin

Glad to see that Unidata has finally made available an updated version of udunits -- I've been using an interim version that they sent me with bug fixes I submitted.

And thanks for fixing the disconnect in `build_bufr.sh` -- the changes look good in the bugfix branch.

**Comment by mmiesch** [comment]
@mer-a-o (and anyone else) - the new gnu and clang docker containers have been built with the above changes and are ready for testing.   They are available on docker hub with the tag `:beta`.    When we confirm that they work, we can re-tag them as latest and incorporate them into the CI.

@srherbener - are the current develop ioda tests sufficient for confirming that the new `bufr` libraries are working or should we also test ioda-converters?

**Comment by mmiesch** [comment]
Doh! already found an error in the .gitconfig - I'll fix that.

**Comment by srherbener** [comment]
@mmiesch, we need to test using ioda-converters to verify that the bufr module is working.

**Comment by mmiesch** [comment]
The gnu docker container is ready for testing now.  The gitconfig issue has been fixed.  All ioda-converters tests pass so bufr is working.  

But, three failures in ufo-bundle - has anyone seen these before?

```
The following tests FAILED:
	238 - test_l95_4dvar.rpcg (Failed)
	239 - test_l95_4dvar.rplanczos (Failed)
	276 - test_l95_simplifiedl95_RPCG (Failed)
	277 - test_l95_simplifiedl95_RPLanczos (Failed)
```

I'll rebuild the clang container next

**Comment by mmiesch** [comment]
Ok - the new clang container is also ready for testing.  Again, it has a tag of `:beta` on Docker hub.   For the clang container, all ioda-converters and ufo-bundle tests pass.  So, that one might be good to start with in incorporating into the CI testing.

Meanwhile, tomorrow I can try to figure out why those l95 tests are failing in the new gnu container.  @cmgas @ytremolet @shlyaeva - have you seen those failures before?

**Comment by ytremolet** [comment]
I've not seen those before. One point that might help is that they all have in common that they do minimisation in observation space, i.e. using ObsVectors.

**Comment by mer-a-o** [comment]
@mmiesch all the tests in fv3-bundle passed inside the clang container on CodeBuild.

**Comment by mmiesch** [comment]
> @mmiesch all the tests in fv3-bundle passed inside the clang container on CodeBuild.

Ok - thanks for confirming.  I have saved the previous clang container on Docker Hub with the `:revert` tag and the new one is now `:latest`

**Comment by cmgas** [comment]
I have not seen these errors before either. Is it segfaulting? Or something else?

**Comment by mmiesch** [comment]
> I have not seen these errors before either. Is it segfaulting? Or something else?

It's strange - it looks like nans might appear in the increment dot product:

```bash
RPCGMinimizer: Estimated Final Jb = OOPS_TRACE Increment<MODEL>::dot_product_with starting
OOPS_TRACE Increment<MODEL>::dot_product_with done
OOPS_TRACE ModelAuxIncrement<MODEL>::dot_product_with starting
OOPS_TRACE ModelAuxIncrement<MODEL>::dot_product_with done
OOPS_TRACE ObsAuxIncrements<OBS>::dot_product_with starting
OOPS_TRACE ObsAuxIncrement<OBS>::dot_product_with starting
OOPS_TRACE ObsAuxIncrement<OBS>::dot_product_with done
OOPS_TRACE ObsAuxIncrements<OBS>::dot_product_with done
nan
RPCGMinimizer outputOOPS_TRACE Increment<MODEL>::print starting

 Valid time: 2010-01-01T03:00:00Z
 Min=nan, Max=nan, Average=nanOOPS_TRACE Increment<MODEL>::print done
OOPS_TRACE ModelAuxIncrement<MODEL>::print starting
OOPS_TRACE ModelAuxIncrement<MODEL>::print done
```

However, I only see this in the gnu container with a RelWIthDebInfo build.  If I build in the gnu container in Debug mode it gose away.  If I build on my Mac (which also uses gnu 9.3 and openmpi - same as the container)  with RelWithDebInfo it passes (making debugging harder).  And, it passes in clang.

**Comment by mmiesch** [comment]
@ytremolet @cmgas - I may have found the problem and, if correct, it is a legitimate bug.

In DualMinimizer::doMinimize, the "starting point augmented part" `vvp` is declared here:
https://github.com/JCSDA-internal/oops/blob/a47cc20415e3ec06693446f49ac1f913ee6763b4/src/oops/assimilation/DualMinimizer.h#L95

But it is not defined before it's used in the linear solve here:
https://github.com/JCSDA-internal/oops/blob/a47cc20415e3ec06693446f49ac1f913ee6763b4/src/oops/assimilation/DualMinimizer.h#L120

On my Mac, this has a value of 2.2e-314 going in, and the test passes.  But, in the container, it's a NaN, which propagates everywhere.  

So, should this be set to zero when it is initialized here?
https://github.com/JCSDA-internal/oops/blob/a47cc20415e3ec06693446f49ac1f913ee6763b4/src/oops/assimilation/DualMinimizer.h#L95

**Comment by mmiesch** [comment]
More to the story.  If I do initialze vvp to zero as I suggested, then the good news is that some of the test failures above now pass.  But, the bad news is that other tests fail:

```
The following tests FAILED:
	118 - test_l95_simplifiedl95_DRPFOM (Failed)
	119 - test_l95_simplifiedl95_DRPLanczos (Failed)
	122 - test_l95_simplifiedl95_IPCG (Failed)
	125 - test_l95_simplifiedl95_PCG (Failed)
	127 - test_l95_simplifiedl95_RPCG (Failed)
	128 - test_l95_simplifiedl95_RPLanczos (Failed)
	189 - test_qg_4densvar (Failed)
	190 - test_qg_4densvar_hybrid (Failed)
```

I'm not sure what the correct value of vvp should be going in

**Comment by cmgas** [comment]
Ok this is weird, because test_l95_simplifiedl95_DRPLanczos shouldn't use that part of the code, should it?

**Comment by cmgas** [comment]
But you are right, vvp is used before it is initialized for example here:
https://github.com/JCSDA-internal/oops/blob/a47cc20415e3ec06693446f49ac1f913ee6763b4/src/oops/assimilation/RPCGMinimizer.h#L190

**Comment by cmgas** [comment]
I tested on my laptop in the stack, and if I initialize vvp=0 in DualMinimizer.h, I do not see test failures.

**Comment by mmiesch** [comment]
> But you are right, vvp is used before it is initialized for example here:
> https://github.com/JCSDA-internal/oops/blob/a47cc20415e3ec06693446f49ac1f913ee6763b4/src/oops/assimilation/RPCGMinimizer.h#L190

Yes - exactly - that's where it is propagating.

**Comment by cmgas** [comment]
This part of the code affects solely RPLanczosMinimizer.h and RPCGMinimizer.h though, it shouldn't break these other tests.

**Comment by cmgas** [comment]
Do you have the error message?

**Comment by mmiesch** [comment]
Ok - I see the problem.  To do the debugging, I had these flags set:

```
 export OOPS_TRAPFPE=1
 export OOPS_ABORTFPE=1
```

Which reveals errors like this (in test_l95_simplifiedl95_DRPFOM):

```
DRPFOM Starting Iteration 1
Caught SIGFPE: floating-point divide by zero
```

And, I can mostly reproduce that on my Mac - if I set those flags, these tests fail:

```
The following tests FAILED:
	119 - test_l95_simplifiedl95_DRPFOM (Failed)
	120 - test_l95_simplifiedl95_DRPLanczos (Failed)
	129 - test_l95_simplifiedl95_RPLanczos (Failed)
	141 - test_qg_verticallocev (Child aborted)
	190 - test_qg_4densvar (Failed)
	191 - test_qg_4densvar_hybrid (Failed)
```

But, if I turn off those flags, then all tests pass in the container and on my Mac

**Comment by mmiesch** [comment]
Oops - I didn't mean to close this quite yet.  @mer-a-o [with this PR in oops](https://github.com/JCSDA-internal/oops/pull/1032), all ufo-bundle tests pass in the new gnu-openmpi docker container (tagged as `:beta` on Docker Hub).  If you confirm that that works, then I will re-tag beta as latest and then we can close this

**Comment by mer-a-o** [comment]
@mmiesch all fv3-bundle tests passed in gnu container. I see the error below when I building fckit and using `-DENABLE_GPROF=ON`. We can still generate code coverage reports if we only build fv3-jedi (`cd build/fv3-bundle && make -j8`) and not the complete bundle. 

```
during IPA pass: profile
--
529 | /build_container/fckit/src/tests/test_abort_main.F90:3:0:
530 |  
531 | 3 \| use fckit_test_abort
532 | \|
533 | internal compiler error: in coverage_begin_function, at coverage.c:656
534 | Please submit a full bug report,
535 | with preprocessed source if appropriate.
536 | See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
537 | make[2]: *** [fckit/src/tests/CMakeFiles/fckit_test_abort.dir/build.make:86: fckit/src/tests/CMakeFiles/fckit_test_abort.dir/test_abort_main.F90.o] Error 1
538 | make[1]: *** [CMakeFiles/Makefile2:6004: fckit/src/tests/CMakeFiles/fckit_test_abort.dir/all] Error 2
```

We have discussed this error in the past but never found a solution: https://github.com/JCSDA-internal/jedi-docs-old/pull/261
So we can go ahead with updating gnu container just need to beware of this error in fckit.

**Comment by mmiesch** [comment]
Thanks @mer-a-o for testing.  In practice we usually just do the codecov tests in each repo, right?  I.e. not the whole bundle at once?  So, the fckit issue shouldn't be much of a problem for CI, right?  But, it may be annoying if people run gcov outside of CI (which I think was the context of that other comment).  Maybe we can revise the docs and tell people how to enable gprof for one JEDI repo at a time so we exclude fckit?

Or, we could consider including fckit in the container & modules if this is a problem.

**Comment by mer-a-o** [comment]
Correct. In CI, we run codecov in each repo and not for the whole bundle. So we are not going to face any problem in CI for now.
