### ISSUE TITLE
restrict access to jscda-ukmo bucket

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/charliecloud#65]
## Description

Restrict access to s3://jcsda-ukmo to modarth and jedi core team

## Requirements

Others should not be able to access it

## Acceptance Criteria (Definition of Done)

permissions are in place and tested

## Dependencies

None

**Comment by mer-a-o** [comment]
Access to jcsda-ukmo bucket is now limited to selected users and CodeBuild
