### ISSUE TITLE
Mac switches off near end of make when using containers

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA/charliecloud#68]
Not sure this is the correct repo to put this issue.

Iuse two containers and the compilation switches off my mac near the end of it.
I have the clang and gnu containers (I haven't tried with the intel but I expect to be the same).
When I turn my mac back on and log back in into singularity I cna finish the few percent left of the make.

I expect this to be caused by an overheating of the computer. It doesn't matter if I use `make` only or `make -j2`.  Is there a way to tell make to use up to certain amount of memory on my mac in order to keep it cool enough?

Also is this something you have experienced as well on singularity. I haven't tried with jedi stack (I never really pushed to finish to install it since the containers are available).

My mac:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,2
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	512 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

Thanks for your help
@mer-a-o @climbfuji

**Comment by climbfuji** [comment]
One thing you can do is look at the Activity Monitor (Applications -> Utilities) to see resource usage (memory, CPU). You can try to throttle things down a bit using `nice -n 19 YOUR COMMAND` which gives it the lowest priority. Not expecting this to make a huge difference, but worth giving it a shot.

**Comment by jeromebarre** [comment]
No difference, mac is still crashing at the end of the make. I'll try to find a solution as this is really not convenient.

**Comment by mer-a-o** [comment]
I have an older Mac so I don't run containers on it. I know @svahl991 uses Singularity containers on his Mac for UM development.

**Comment by jeromebarre** [comment]
I'm looking at using `ulimit` maybe that will work.

**Comment by svahl991** [comment]
How long does the compiling take? Does your computer maybe go to sleep or otherwise shut down something for power-saving? I have had troubles with Vagrant/Singularity "hanging" when my Mac goes to sleep, so I disable that feature when I have the VM running.

Other than that, I've never experienced anything like what you describe. My Mac is a bit beefier than the one you're working with, though.

**Comment by jeromebarre** [comment]
Unfortunately, turning off all energy saving options didn't solve the issue. I had a try and my mac started to freeze more and more up to a total freeze and then fan goes on very loud for a couple seconds and mac shuts off... Maybe using `ulimit` will solve this. I'll try tonight or tomorrow. Beefier mac is an option if JCSDA provides me one. Or stop working on my local machine.

**Comment by climbfuji** [comment]
Can you enlighten me please how ulimit is supposed to help?

**Comment by jeromebarre** [comment]
My understanding is that with ulimit you can control the amount of ressources used by a process. Given your comment above there might be something I am missing or not understanding.

```
`ulimit --help
ulimit: ulimit [-SHabcdefiklmnpqrstuvxPT] [limit]
    Modify shell resource limits.
```

    Provides control over the resources available to the shell and processes
    it creates, on systems that allow such control.

    Options:
      -S	use the `soft' resource limit
      -H	use the `hard' resource limit
      -a	all current limits are reported
      -b	the socket buffer size
      -c	the maximum size of core files created
      -d	the maximum size of a process's data segment
      -e	the maximum scheduling priority (`nice')
      -f	the maximum size of files written by the shell and its children
      -i	the maximum number of pending signals
      -k	the maximum number of kqueues allocated for this process
      -l	the maximum size a process may lock into memory
      -m	the maximum resident set size
      -n	the maximum number of open file descriptors
      -p	the pipe buffer size
      -q	the maximum number of bytes in POSIX message queues
      -r	the maximum real-time scheduling priority
      -s	the maximum stack size
      -t	the maximum amount of cpu time in seconds
      -u	the maximum number of user processes
      -v	the size of virtual memory
      -x	the maximum number of file locks
      -P	the maximum number of pseudoterminals
      -T	the maximum number of threads

    Not all options are available on all platforms.

    If LIMIT is given, it is the new value of the specified resource; the
    special LIMIT values `soft', `hard', and `unlimited' stand for the
    current soft limit, the current hard limit, and no limit, respectively.
    Otherwise, the current value of the specified resource is printed.  If
    no option is given, then -f is assumed.

    Values are in 1024-byte increments, except for -t, which is in seconds,
    -p, which is in increments of 512 bytes, and -u, which is an unscaled
    number of processes.

    Exit Status:
    Returns success unless an invalid option is supplied or an error occurs.`

**Comment by jeromebarre** [comment]
Currently what is set to default on my VM with vagrant:
```
ulimit -a

core file size          (blocks, -c) 0

data seg size           (kbytes, -d) unlimited

scheduling priority             (-e) 0

file size               (blocks, -f) unlimited

pending signals                 (-i) 47703

max locked memory       (kbytes, -l) 65536

max memory size         (kbytes, -m) unlimited

open files                      (-n) 1024

pipe size            (512 bytes, -p) 8

POSIX message queues     (bytes, -q) 819200

real-time priority              (-r) 0

stack size              (kbytes, -s) 8192

cpu time               (seconds, -t) unlimited

max user processes              (-u) 47703

virtual memory          (kbytes, -v) unlimited

file locks                      (-x) unlimited
```

So things set to unlimited such as max memory size and virtual memory could be a problem. But I am not an expert here...

**Comment by jeromebarre** [comment]
Also another solution is to modify the vagrant file, currently there this section commented:
```
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
```

**Comment by jeromebarre** [comment]
or something like this to control cpu usage
```
config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
end
```
to set a cap to 50% of cpu usage. This might be the correct solution as I think the mac shut down is probably due to a cpu overload.

**Comment by jeromebarre** [comment]
Capping cpu and ram on the vagrant file seems to solve the issue so far. I am closing the issue but might reopen if this still occurs.

**Comment by climbfuji** [comment]
> Capping cpu and ram on the vagrant file seems to solve the issue so far. I am closing the issue but might reopen if this still occurs.

Wow, didn't expect that. Great detective work!

**Comment by climbfuji** [comment]
If your problem is really that the cpu overheats, then I’d be surprised if limiting the memory etc helps - but it wouldn’t be the first time to be surprised, and testing your hypothesis won’t take long.
