### ISSUE TITLE
ecbuild missing from latest image

### ISSUE THREAD

**Issue by yaswant** [JCSDA/charliecloud#69]
## ecbuild missing from latest image (30 Sept 2022) 

In the latest Singularity images (from both Sylabs and Docker hub) `ecbuild` seems to be missing.  This is breaking some container-image-dependent workflow.  The current work around is to use image with revert tag.  

Can we have a patch sooner if possible, please?

**Comment by climbfuji** [comment]
@mer-a-o Didn't we test (manuall) and don't we use the containers in CI routinely? They wouldn't work if they didn't have `ecbuild`?

**Comment by yaswant** [comment]
@climbfuji - I was going to ask the same question.

**Comment by climbfuji** [comment]
@yaswant In the CI tests, we need to run the following for the clang container:
```
source /etc/profile.d/z10_spack_environment.sh
```
See https://github.com/JCSDA-internal/fv3-jedi/blob/develop/CI/buildspec_clang.yml

**Comment by yaswant** [comment]
Thanks @climbfuji that's what we were missing.  By the way, why is that not sourced automatically when the container is loaded?

**Comment by climbfuji** [comment]
Please let us know once you are sure the containers work for you, then we can close this issue. Thanks!

**Comment by yaswant** [comment]
will do. thanks!

**Comment by yaswant** [comment]
@climbfuji I am still straggling to get things work using the latest image

```
singularity shell --disable-cache -e jedi-gnu-openmpi-dev_latest.sif
Singularity> ecbuild --version
bash: ecbuild: command not found

Singularity> source /etc/profile.d/z10_spack_environment.sh 
Singularity> ecbuild --version
ecbuild version 3.6.5

Singularity> cmake --version
Illegal instruction

Singularity> atlas --info
Illegal instruction

Singularity> h5cc -dumpversion
/opt/view/h5cc
dir is /opt/view
Illegal instruction
Illegal instruction
Singularity> 
```

**Comment by climbfuji** [comment]
I have not used the singularity containers myself, I've only used the original docker containers. @mer-a-o how did you test the singularity containers after creating them from the docker containers?

**Comment by yaswant** [comment]
@climbfuji there are two instances:
1. from [DockerHub](https://hub.docker.com/r/jcsda/docker-gnu-openmpi-dev) - we use in github build/test pipeline
2. from [Sylabs cloud](https://cloud.sylabs.io/library/jcsda/public/jedi-gnu-openmpi-dev) - verified and used on our local network.  My example above was based on this.

If the same container image is used for JEDI CI, I believe we are missing something simple here?

**Comment by mer-a-o** [comment]
@climbfuji This is the same error @fmahebert reported with running Singularity + Vagrant on Mac. @yaswant Are you using Vagrant with Singularity?

**Comment by yaswant** [comment]
@mer-a-o no I don't.

**Comment by climbfuji** [comment]
I wonder if we should try creating the singularity container straight from spack (in parallel to the docker container)

**Comment by mer-a-o** [comment]
@yaswant Where are you running Singularity? Can you please provide more info? Is it possible to use Docker instead of Singularity?

**Comment by yaswant** [comment]
The CI workflow is running on MetOffice/GitHub - I am afraid this is a private repo.  Here we use the Docker image.

And for Singularity, we are running on our local Linux network.

**Comment by mer-a-o** [comment]
@yaswant, thanks. Was the issue resolved with Docker/CI workflow after `source /etc/profile.d/z10_spack_environment.sh`?

I will work on the Singularity problem. Meanwhile, I believe you can use the old Singularity container (revert tag). You will need to build atlas 0.30.0 in it though. 
```
singularity pull  library://jcsda/public/jedi-gnu-openmpi-dev:revert
```
Or depending on your local linux network setup you may be able to use Docker.

**Comment by yaswant** [comment]
> @yaswant, thanks. Was the issue resolved with Docker/CI workflow after `source /etc/profile.d/z10_spack_environment.sh`?

No. 

Therefore, we continue with the old image -> `revert` tag.

We don't have the flexibility to run Docker image on our Linux network.  So when you patch the Singularity image I should be able to test it.

**Comment by mer-a-o** [comment]
@yaswant, we updated the Singularity and Docker images, please see [here](https://github.com/NOAA-EMC/spack-stack/pull/391) for details. Shumlib is now included in the images. Can you please test them when you get a chance?

**Comment by yaswant** [comment]
Thanks @mer-a-o - I'll take a look asap.  Do we have the updated docker images available on DockerHub as well?

**Comment by mer-a-o** [comment]
Thanks @yaswant. I just updated the "latest" tags on DockerHub.

**Comment by yaswant** [comment]
@mer-a-o  - still failing to find `ecbuild`

![image](https://user-images.githubusercontent.com/2984440/202421090-7e2b8b26-fcbe-43be-9c60-817b1e8bf5d6.png)

**Comment by mer-a-o** [comment]
@yaswant You will still need to source the Spack env file. 
`source /etc/profile.d/z10_spack_environment.sh`

I'm setting up GitHub Actions for our ewok repository and I'm loading container at the beginning of the job [there](https://github.com/JCSDA-internal/ewok/blob/c6b9cec66fd946da5ac380fbb590e4e360c7a150/.github/workflows/run_ec2_container.yaml#L24). Have you considered doing something similar? Please take a look at my yaml file [here](https://github.com/JCSDA-internal/ewok/blob/feature/gta-container/.github/workflows/run_ec2_container.yaml)

**Comment by yaswant** [comment]
@mer-a-o Ah! I see.  I thought we agreed that to be sourced automatically at `docker run` or `singularity shell`.  If possible to make a change we'd prefer that,

- Inclusion of shumlib is very welcome 👍🏽 
- Update to all ecmwf libraries also welcome 👍🏽 

I can remove them from our build ci to save some time.

Thank you for the fix.

**Comment by yaswant** [comment]
Build has not finished yet, but I see this warning 

```
/usr/bin/ld: warning: /tmp/root/spack-stage/spack-stage-shumlib-macos_clang_linux_intel_port-7nbwz2c7e2wsbypdgs22pwm7ga2lbkag/spack-src/spack-build/lib/libshum_string_conv.so, needed by /opt/view/lib/libshum_byteswap.so, not found (try using -rpath or -rpath-link)
```

**Comment by climbfuji** [comment]
> Build has not finished yet, but I see this warning
> 
> ```
> /usr/bin/ld: warning: /tmp/root/spack-stage/spack-stage-shumlib-macos_clang_linux_intel_port-7nbwz2c7e2wsbypdgs22pwm7ga2lbkag/spack-src/spack-build/lib/libshum_string_conv.so, needed by /opt/view/lib/libshum_byteswap.so, not found (try using -rpath or -rpath-link)
> ```

Did the build finish and did the code run? Asking because it says "warning"

**Comment by yaswant** [comment]
Hi @climbfuji yes the build succeed, but most of the unit opsinputs tests failed like:


```
  3/117 Test   #3: test_opsinputs_varobswriter_001_VarField_pstar ............................***Failed    2.06 sec
/tmp/opsinputs-ci-build-PBji14/bin/test_OpsInputsFilters.x: error while loading shared libraries: /tmp/root/spack-stage/spack-stage-shumlib-macos_clang_linux_intel_port-7nbwz2c7e2wsbypdgs22pwm7ga2lbkag/spack-src/spack-build/lib/libshum_string_conv.so: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[53278,1],0]
  Exit code:    127
--------------------------------------------------------------------------
```
I think shumlib is build correctly in the container, but `/opt/view/lib` is missing from `LD_LIBRARY_PATH` and the opsinputs application is looking at wrong place for it.  We can fix this easily (add `/opt/view/lib` to `LD_LIBRARY_PATH` in `/etc/profile.d/z10_spack_environment.sh`).  If you have time please take a look. In the mean time, I'am reverting to our own recipe for shumlib in ci-build and testing now...

Ps: _This is the case for both docker and Singularity images._

**Comment by climbfuji** [comment]
> Hi @climbfuji yes the build succeed, but most of the unit opsinputs tests failed like:
> 
> ```
>   3/117 Test   #3: test_opsinputs_varobswriter_001_VarField_pstar ............................***Failed    2.06 sec
> /tmp/opsinputs-ci-build-PBji14/bin/test_OpsInputsFilters.x: error while loading shared libraries: /tmp/root/spack-stage/spack-stage-shumlib-macos_clang_linux_intel_port-7nbwz2c7e2wsbypdgs22pwm7ga2lbkag/spack-src/spack-build/lib/libshum_string_conv.so: cannot open shared object file: No such file or directory
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> mpiexec detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>   Process name: [[53278,1],0]
>   Exit code:    127
> --------------------------------------------------------------------------
> ```
> 
> I think shumlib is build correctly in the container, but `/opt/view/lib` is missing from `LD_LIBRARY_PATH` and the opsinputs application is looking at wrong place for it. We can fix this easily (add `/opt/view/lib` to `LD_LIBRARY_PATH` in `/etc/profile.d/z10_spack_environment.sh`). If you have time please take a look. In the mean time, I'am reverting to our own recipe for shumlib in ci-build and testing now...
> 
> Ps: _This is the case for both docker and Singularity images._

Thanks, Yash. Yes, the shumlib build system is wonky, not following any of the standard build types, and looks like spack doesn't know how to handle it well. We can hopefully update the spack recipe for shumlib and get the build done right.

**Comment by yaswant** [comment]
@climbfuji an update: modifying LD_LIBRARY_PATH deosnot work.  I guess spack build has set incorrect `RPATH` for `shumlib` ?

**Comment by climbfuji** [comment]
> @climbfuji an update: modifying LD_LIBRARY_PATH deosnot work. I guess spack build has set incorrect `RPATH` for `shumlib` ?

Hmm, so what happens is that that the code gets built in a certain directory `/tmp/root/spack-stage/spack-stage-shumlib-macos_clang_linux_intel_port-7nbwz2c7e2wsbypdgs22pwm7ga2lbkag/spack-src/spack-build/` and then installed in a different location. spack should relocate the rpath and it seems it does that correctly everywhere else, because we install and use shumlib on other systems (HPCs, macOS). We'll have to look into that.

**Comment by climbfuji** [comment]
@yaswant @mer-a-o I just uploaded a new container `469205354006.dkr.ecr.us-east-1.amazonaws.com/jedi-clang-mpich-dev:test` to our AWS ECR container registry. This should fix the shumlib problem described above. Is that something you can try?

**Comment by climbfuji** [comment]
The CI containers have been updated ("latest" tags) and used successfully in the CI tests. Manual inspection shows that the paths to shumlib are now correct. I am closing this issue as completed. If another problem shows up, please create an issue in the appropriate repository (https://github.com/noaa-emc/spack-stack for issues related to spack-stack, bundle/code repos for other issues as appropriate).
